nexus-repository-manager:
  nexus:
    docker:
      enabled: true
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "3Gi"

  persistence:
    enabled: false

  service:
    type: NodePort
